longhorn:
  repoURL: https://charts.longhorn.io/
  values: |
    preUpgradeChecker:
      jobEnabled: false
metrics-server:
  repoURL: https://kubernetes-sigs.github.io/metrics-server/
  values: |
    apiService:
      insecureSkipTLSVerify: true
    args:
      - --kubelet-insecure-tls
trivy-operator:
  repoURL: https://aquasecurity.github.io/helm-charts/
